# Generated by Django 3.2 on 2025-05-03 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_alter_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='parking_spots/'),
        ),
        migrations.AddField(
            model_name='location',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
