# Generated by Django 3.2 on 2025-05-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20250503_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
