# Generated by Django 3.2 on 2025-05-29 10:37

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_location_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(default='FREE', max_length=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default='FREE', max_digits=6)),
                ('daily_rate', models.DecimalField(decimal_places=2, default='FREE', max_digits=6)),
                ('payment_methods', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='location',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.payment'),
        ),
    ]
